### ISSUE TITLE
The test py has error at the beginning

### ISSUE THREAD

**Issue by BinglinW** [MathEXLab/PySPOD#30]
Hi,
when I run the test py file, there exists an error because there is no _spod_
```
from pyspod.spod.standard  import Standard  as spod_standard
from pyspod.spod.streaming import Streaming as spod_streaming
```
May I know how to solve it?

**Comment by mengaldo** [comment]
Thank you for the query. Can you provide more information (e.g., the test py file)?

**Comment by BinglinW** [comment]
> Thank you for the query. Can you provide more information (e.g., the test py file)?
\PySPOD-main\tests\test_utils_serial.py
```
line17 ModuleNotFoundError: No module named 'pyspod.spod'
```
\PySPOD-main\tutorials\tutorial1\tutorial1.py
```
line 15 from pyspod.spod.standard  import Standard  as spod_standard
ModuleNotFoundError: No module named 'pyspod.spod'
```

**Comment by mengaldo** [comment]
Thank you. Can you try installing the library using: ```python3 setup.py install```

**Comment by BinglinW** [comment]
> Thank you. Can you try installing the library using: `python3 setup.py install`

I have already installed the pyspod. If I run "import pyspod", it is ok. 

However, there is no pyspod.spod. In C:\Users\wbl\AppData\Roaming\Python\Python38\site-packages\pyspod, there is no file named spod, only with  spod_base, spod_low_ram, et.al.

![image](https://user-images.githubusercontent.com/84228480/207241784-4abcc48f-8d38-4b13-8ac9-dfdab44945a2.png)

**Comment by mengaldo** [comment]
I see, note that we deployed a new version, that we are currently testing. The new version is parallel. I suggest that you clone the new repository, and run the command  ```python3 setup.py install```

tutorial1 should then work.

**Comment by mengaldo** [comment]
@BinglinW can I close the issue?

**Comment by BinglinW** [comment]
> @BinglinW can I close the issue?
yes, thanks for your help.

**Comment by mengaldo** [comment]
Great, thank you.
