### ISSUE TITLE
Weights shape error

### ISSUE THREAD

**Issue by FrankFrank9** [MathEXLab/PySPOD#45]
Hello,

when I run in parallel the SPOD with a custom weighting matrix (area of the elements) I get the following error but everything is fine when I run in serial mode. Do you have any idea on that?
```
 ValueError: parameter ``weights`` must be cast into 1d array with dimension equal to flattened spatial dimension of data.
    raise ValueError(
    raise ValueError(
ValueError: parameter ``weights`` must be cast into 1d array with dimension equal to flattened spatial dimension of data.
    raise ValueError(
ValueError: parameter ``weights`` must be cast into 1d array with dimension equal to flattened spatial dimension of data.
    raise ValueError(
ValueError: parameter ``weights`` must be cast into 1d array with dimension equal to flattened spatial dimension of data.
    raise ValueError(
ValueError: parameter ``weights`` must be cast into 1d array with dimension equal to flattened spatial dimension of data.
    raise ValueError(
ValueError: parameter ``weights`` must be cast into 1d array with dimension equal to flattened spatial dimension of data.
    raise ValueError(
ValueError: parameter ``weights`` must be cast into 1d array with dimension equal to flattened spatial dimension of data.
ValueError: parameter ``weights`` must be cast into 1d array with dimension equal to flattened spatial dimension of data.
    raise ValueError(
ValueError: parameter ``weights`` must be cast into 1d array with dimension equal to flattened spatial dimension of data.
    raise ValueError(
ValueError: parameter ``weights`` must be cast into 1d array with dimension equal to flattened spatial dimension of data
```

**Comment by dalcinl** [comment]
What's the shape of your weights? Can you try passing `weithgs.reshape(-1)` instead?

**Comment by dalcinl** [comment]
> and my time series data shape is
> 
> `(200, 278946, 5)`

So do you have 200 time samples, each comprising of 278946 spatial points with 5 variables per point?

I think the weights correspond to just to spatial points and not variables, therefore you should provide 278946 weights, and not 278946 * 5 = 1394730. @mrogowski Can you confirm?

**Comment by mrogowski** [comment]
We should support weight per spatial point per variable. Looking quickly at the code, I think we may have a bug. We tested the one variable branch heavily in parallel, but not so much for data with multiple variables. @FrankFrank9, what is the format of your data? Could you come up with a simple reproducer?

**Comment by mrogowski** [comment]
Can you try to run with [this change](https://github.com/MathEXLab/PySPOD/pull/48) in PySPOD?

**Comment by dalcinl** [comment]
> Unfortunately I can't make an easy reproducible thing.

Not even using random data with shapes that match your data?

**Comment by mrogowski** [comment]
I generated random data:
```
data matrix X (200, 278946, 5)
weights (278946, 1, 5)
```
and tried with 7, 8, 9, 10, 11, 12 processes. All seem to have worked. Any reproducer would be very helpful to assist you.

**Comment by dalcinl** [comment]
Oh, but then that means we can do better, that is, add the missing axis, right Marcin?

**Comment by mrogowski** [comment]
> Now it works, the weights need the second axis as well , mine were just (npts, nvars).
> Thanks for looking into this !

Good to hear! Like I said before, most of the runs we did so far were for 1 variable 2D data, so you may spot some issues with 1D and/or multivariable data. Let us know and we'll try to fix it.

**Comment by mrogowski** [comment]
> Oh, but then that means we can do better, that is, add the missing axis, right Marcin?

I'll try to reproduce the issue that @FrankFrank9 ran into and fix it. I used `(278946, 1, 5)` because that's what I got from `utils_weights.geo_trapz_2D`. It just happens that it was the problem.

**Comment by mrogowski** [comment]
> I'll try to reproduce the issue that @FrankFrank9 ran into and fix it.

I couldn't - worked for me with `(278946, 5)` weights as well.

**Comment by mrogowski** [comment]
`pip install pyspod` would install the last published version which does not contain this fix. You'd need to `pip install git+https://github.com/MathEXLab/PySPOD@refs/pull/48/head` or manually clone the repo from the PR and `pip install` it.
